// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2023 Rerrah

#pragma once

#include <JuceHeader.h>
#include <ymfm_opn.h>

#include <atomic>
#include <memory>
#include <mutex>
#include <vector>

#include "../ranged_value.h"
#include "./parameter/parameter.h"
#include "keyboard.h"

namespace audio {
struct Register;
}

namespace audio {
/**
 * @brief Audio source class for FM part.
 * @note Note-on and -off is sensitive on MIDI channel, but pitch bend and pitch
 * bend sensitivity is insensitive.
 */
class FmAudioSource : public juce::AudioSource {
 public:
  /**
   * @brief Constructor.
   */
  FmAudioSource();

  /**
   * @brief Destructor.
   */
  ~FmAudioSource() override;

  /**
   * @brief Get synthesis rate of FM part.
   * @return FM synthesis rate.
   */
  double synthesisRate() const;

  /**
   * @brief Prepare audio source to play.
   * @details Reset emulation.
   */
  void prepareToPlay(int samplesPerBlockExpected,
                     double /*sampleRate*/) override;

  /**
   * @brief Release resources.
   */
  void releaseResources() override {}

  /**
   * @brief Fill samples to a buffer in given channel info.
   * @param[in] bufferToFill Channel info which has a buffer to be stored
   * samples.
   */
  void getNextAudioBlock(
      const juce::AudioSourceChannelInfo& bufferToFill) override;

  /**
   * @brief Reset internal state.
   */
  void reset();

  // [Changes] -----------------------------------------------------------------
  /**
   * @brief Try to reserve parameter change.
   * @param[in] value Parameter value.
   * @return @c true if change is accepted, otherwise @c false.
   */
  bool tryReserveParameterChange(
      const parameter::PitchBendSensitivityValue& value);
  bool tryReserveParameterChange(const parameter::FeedbackValue& value);
  bool tryReserveParameterChange(const parameter::AlgorithmValue& value);

  /**
   * @brief Try to reserve parameter change.
   * @param[in] slotAndValue Slot number and parameter value.
   * @return @c true if change is accepted, otherwise @c false.
   */
  bool tryReserveParameterChange(
      const parameter::SlotAndValue<parameter::OperatorEnabledValue>&
          slotAndValue);
  bool tryReserveParameterChange(
      const parameter::SlotAndValue<parameter::AttackRateValue>& slotAndValue);
  bool tryReserveParameterChange(
      const parameter::SlotAndValue<parameter::DecayRateValue>& slotAndValue);
  bool tryReserveParameterChange(
      const parameter::SlotAndValue<parameter::SustainRateValue>& slotAndValue);
  bool tryReserveParameterChange(
      const parameter::SlotAndValue<parameter::ReleaseRateValue>& slotAndValue);
  bool tryReserveParameterChange(
      const parameter::SlotAndValue<parameter::SustainLevelValue>&
          slotAndValue);
  bool tryReserveParameterChange(
      const parameter::SlotAndValue<parameter::TotalLevelValue>& slotAndValue);
  bool tryReserveParameterChange(
      const parameter::SlotAndValue<parameter::KeyScaleValue>& slotAndValue);
  bool tryReserveParameterChange(
      const parameter::SlotAndValue<parameter::MultipleValue>& slotAndValue);
  bool tryReserveParameterChange(
      const parameter::SlotAndValue<parameter::DetuneValue>& slotAndValue);

  /**
   * @brief Try to reserve MIDI message after triggering.
   * @param[in] message MIDI message
   * @return @c true if given message was used. If it was discarded, returns
   * @c false.
   */
  bool tryReserveChangeFromMidiMessage(const juce::MidiMessage& message);

  /**
   * @brief Change audio source state by executing reserved MIDI messages and
   * some changes.
   */
  void triggerReservedChanges();

 private:
  /// Emulator.
  std::unique_ptr<ymfm::ym2608> ym2608_;

  /// Emulator interface.
  ymfm::ymfm_interface interface_;

  /// Temporary buffer to store samples generated by the emulator.
  std::vector<ymfm::ym2608::output_data> outputDataBuffer_;

  // [Polyphony Control] -------------------------------------------------------

  /// Manager of note-on and -off.
  Keyboard keyboard_;

  // [Audio State] -------------------------------------------------------------

  /// Current pitch bend.
  int pitchBend_{0};

  /// Mutex for parameters.
  std::mutex parameterMutex_;

  /// Semitone range for pitch bend.
  parameter::PitchBendSensitivityValue pitchBendSensitivity_{2};

  // State of tone parameters.
  FmParameters toneParameterState_;

  /// RPN/NRPN detector.
  juce::MidiRPNDetector rpnDetector_;

  /// Operator mask which should be note-on.
  std::atomic_uint8_t noteOnMask_{0xf0u};

  // [Register Change] ---------------------------------------------------------

  /// Queue of register changes.
  std::vector<Register> reservedChanges_;
  std::mutex reservedChangesMutex_;

  /**
   * @brief Reserve register changes related on note-on event.
   * @param[in] assignment Details of note-on event.
   * @return @c true if the reservation is success, otherwise @c false.
   */
  bool reserveNoteOn(const NoteAssignment& assignment);

  /**
   * @brief Reserve register changes related on note-off event.
   * @param[in] assignment Details of note-off event.
   * @return @c true if the reservation is success, otherwise @c false.
   */
  bool reserveNoteOff(const NoteAssignment& assignment);

  /**
   * @brief Reserve register changes for all note-on notes related on pitch
   * change event.
   * @return @c true if the reservation is success, otherwise @c false.
   */
  bool reservePitchChange();

  /**
   * @brief Reserve register changes for a specific note related on pitch change
   * event.
   * @param[in] assignment Details of note whose pitch should be changed.
   * @return @c true if the reservation is success, otherwise @c false.
   */
  bool reservePitchChange(const NoteAssignment& assignment);

  /**
   * @brief Reserve register changes related to update tone parameters.
   */
  void reserveUpdatingAllToneParameter();

  JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(FmAudioSource)
};
}  // namespace audio
